#pic12_unit.py
#Routines for building unit tests for the pic12 processor
from SCons.Script import *
from SCons.Environment import Environment
import os
import os.path
import utilities

sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'python'))
from gpysim import log
import hex8.symbols

def build_exec_unittest(test_files, name, chip):
	"""
	Build the unit test described by the source files <test_files>.  Build the 
	MIB12 executive hex file and then a hex file containing the unit test,
	join them together and build gpsim script to execute the test.  Create a combined
	symbol file for the executive and test so that the log file generated by the test
	can be interpreted and addressed mapped to functions.
	"""

	mib12conf = utilities.MIB12Config()

	dirs = mib12conf.build_dirs(chip)

	builddir = dirs['build']
	testdir = os.path.join(dirs['test'], name, 'objects')
	finaldir = dirs['output']
	outdir = os.path.join(dirs['test'], name)
	
	env = Environment(tools=['xc8_compiler', 'patch_mib12', 'merge_mib12_app', 'merge_mib12_sym', 'gpsim_runner'], ENV = os.environ)
	env.AppendENVPath('PATH','../../tools/scripts')

	incs = []
	incs.append('.')
	incs.append('src')
	incs.append('src/mib')
	incs.append(testdir)

	env['INCLUDE'] = incs

	#Copy over the symbol file so we can reference it
	symfile = Command(os.path.join(testdir, 'mib12_executive_symbols.h'),  os.path.join(builddir, 'mib12_executive_symbols.h'), Copy("$TARGET", "$SOURCE"))
	execsymtab = Command(os.path.join(testdir, 'symbols.stb'),  os.path.join(builddir, 'mib12_executive_symbols.stb'), Copy("$TARGET", "$SOURCE"))

	symtab = env.merge_mib12_symbols([os.path.join(outdir, 'symbols.stb')], [execsymtab, os.path.join(testdir, name + '_app.sym')])

	#Load in all of the xc8 configuration from build_settings
	mib12conf.config_env_for_app(env, chip)
	alias,define,sim = mib12conf.find_chip_info(chip)

	env['TESTCHIP'] = sim
	env['TESTNAME'] = name
	env['TESTAPPEND'] = mib12conf.get_chip_name(chip)

	srcfiles = test_files
	srcfiles += ['../test/pic12/exec_harness/mib12_exec_unittest.c', '../test/pic12/exec_harness/mib12_exec_unittest_startup.as', '../test/pic12/gpsim_logging/test_log.as']

	apphex = env.xc8(os.path.join(testdir, name + '_app.hex'), srcfiles)
	env.Depends(apphex[0], symfile)

	localexec = env.Command(os.path.join(testdir, 'mib12_executive_local.hex'), os.path.join(builddir, 'mib12_executive_patched.hex'), action='python ../../tools/scripts/patch_start.py $SOURCE $TARGET')
	outhex = env.merge_mib12_app(os.path.join(outdir, name + '.hex'), [localexec, apphex[0]])

	outscript = env.Command([os.path.join(outdir, 'test.stc')], [outhex], action=build_unittest_script)

	raw_results = env.gpsim_run(build_logfile_name(env), outscript)
	formatted_log = env.Command([build_formatted_log_name(env), build_status_name(env)], [raw_results, symtab], action=process_unittest_log)

	env.Command(build_formatted_log_name(env) + 'nonexistant', [], Delete(raw_results))

	#Also remember to remove the test directory when cleaning
	env.Clean(outscript, testdir)
	env.Clean(outscript, outdir)

def build_unittest_script(target, source, env):
	"""
	Build a gpsim script to execute this unit test
	"""

	logfile = os.path.join('..', '..', 'output', env['TESTNAME'] + '_' + env['TESTAPPEND'] + '.raw')

	sim = env['TESTCHIP']
	name = env['TESTNAME']

	with open(str(target[0]), "w") as f:
		print "Hello"
		f.write('processor %s\n' % sim)
		f.write('load s %s\n' % os.path.basename(str(source[0])))
		f.write('break w 0x291, reg(0x291) == 0x00\n')
		f.write('log w %s.ccpr1l\n' % sim)
		f.write('log w %s.ccpr1h\n' % sim)
		f.write("log on '%s'\n" % logfile)
		f.write('run\n')

def process_unittest_log(target, source, env):
	"""
	Source should be the unprocessed log file and the symbol file (stb) for assigning addresses to functions.
	"""
	symtab = hex8.symbols.XC8SymbolTable(str(source[1]))
	lf = log.LogFile(str(source[0]), symtab=symtab)
	lf.save(str(target[0]))
	lf.save_status(str(target[1]))


def build_logfile_name(env):
	return os.path.join('build', 'test', 'output', env['TESTNAME'] + '_' + env['TESTAPPEND'] + '.raw')

def build_formatted_log_name(env):
	return os.path.join('build', 'test', 'output', env['TESTNAME'] + '_' + env['TESTAPPEND'] + '.log')

def build_status_name(env):
	return os.path.join('build', 'test', 'output', env['TESTNAME'] + '_' + env['TESTAPPEND'] + '.status')
