import os

incs = []
incs.append('.')
incs.append('src')
incs.append('src/mib')


Import('env')
env['INCLUDE'].extend(incs)
env['NO_STARTUP'] = True

asm_sources = []
peri = ['../../../shared/pic12/src/peripheral/spi2.c']
api = ['../../../shared/pic12/src/mib12_api.as']

srcfiles = asm_sources + Glob('./*.c') + peri  + [env['MIBFILE']] + api


target = env.xc8('mib12_app_module.hex', srcfiles)
symtab = env.build_symbols(['mib12_app_module_symbols.h', 'mib12_app_module_symbols.stb', 'mib12_app_module_rom_summary.txt'],['mib12_app_module.sym'])

Clean(target, ['#funclist', '#l.obj'])