---

:project:
  :use_exceptions: FALSE
  #:use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :release_build: TRUE
  :test_file_prefix: test_
  :use_mocks: TRUE
  :output: libPIC24shared.a

:release_build:
  :use_assembly: TRUE


:extension:
  :executable: .a 

:paths:
  :test:
    - +:test/**
  :source:
    - +:./src/**
    - +:../portable/**
  :include:
    #- +:../../../tools/**

:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :commmon: &common_defines
    - UNITY_INT_WIDTH=16
    - CMOCK_MEM_INDEX_TYPE=uint16_t
    - CMOCK_MEM_PTR_AS_INT=uint16_t
    - CMOCK_MEM_ALIGN=1
    - CMOCK_MEM_SIZE=1024
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST
:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback

:tools:
  :release_compiler:
    :executable: xc16-gcc
    :arguments:
      - -mcpu=$ : PROC
      - -x c
      #- -S
      - -c
      - ${1}
      - -o ${2}
      - -I"$": COLLECTION_PATHS_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_RELEASE_TOOLCHAIN_INCLUDE
      - -D$: COLLECTION_DEFINES_RELEASE_AND_VENDOR
      - -Wall
      #- -Werror
      - -O1
      #- -g debug
  :release_assembler:
    :executable: xc16-gcc
    :arguments:
      - -mcpu=$ : PROC
      - -c
      - ${1}
      - -o ${2}
      - -I"$": COLLECTION_PATHS_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_RELEASE_TOOLCHAIN_INCLUDE
      - -D$: COLLECTION_DEFINES_RELEASE_AND_VENDOR
      - -D$ : PROC_DEFINE
      - -Wall
      - -O1
      - -Wa,--no-relax
  :release_linker:
    :executable: xc16-ar
    :arguments:
      - qc
      - build/release/libPIC24shared_$.a : TARGET_EXT
      - ${1}
  :test_compiler:
    :executable: xc16-gcc
    :arguments:
      - -mcpu=$ : PROC
      - -x c
      - -c
      - ${1}
      - -o ${2}
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -D$ : PROC_DEFINE
      - -Wall
      #- -Werror  # We can't keep this on during test becuase of a CMock pointer issue
      - -O0

  :test_linker:
    :executable: xc16-gcc
    :arguments:
      - -mcpu=$ : PROC
      - ${1}
      - -o "./build/test/TestBuild.out"
      - -Wl,-Tp24FJ64GA306.gld,-Map=./build/release/TestOutput.map,--report-mem

  :test_fixture:
    :executable: ruby
    :name: "Microchip simulator test fixture"
    :stderr_redirect: :win #inform Ceedling what model of $stderr capture to use
    :arguments:
      - test/simulation/sim_test_fixture.rb

  :test_includes_preprocessor:
    :executable: xc16-gcc
    :arguments:
      - -E
      - -MM
      - -MG
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -D$ : PROC_DEFINE
      - -D$: DEFINES_TEST_PREPROCESS
      - ${1}

  :test_file_preprocessor:
    :executable: xc16-gcc
    :arguments:
      - -E
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -D$: DEFINES_TEST_PREPROCESS
      - -D$ : PROC_DEFINE
      - ${1}
      - -o ${2}

:plugins:
  :load_paths:
    - ../../../tools/ceedling/plugins
    - ../../../tools/ceedling-plugins
  :enabled:
    - stdout_pretty_tests_report
...
