import os
import utilities
import pic24

module_name = 'libpic24'
family_name = 'mib24'


#Build for all targets
family = utilities.get_family(family_name)
family.for_all_targets(module_name, lambda x: pic24.build_library(module_name, x))

#Build all unit tests
#unit_test.build_units('test', utilities.get_module_targets(module_name), subclass=unit_test12.Pic12UnitTest)

Alias('release', os.path.join('build', 'output'))
Alias('test', os.path.join('build', 'test', 'output'))
Default('release')
