import os

incs = []
incs.append('.')
incs.append('src')
incs.append('src/mib')


Import('env')
env['INCLUDE'].extend(incs)
env['NO_STARTUP'] = True

asm_sources = ['app_startup.as', 'mib/mib12_api.as']
peri = ['../../../shared/pic12/src/peripheral/adc.c', '../../../shared/pic12/src/peripheral/timer1.c']

srcfiles = asm_sources + Glob('./*.c') + peri  + [env['MIBFILE']]


target = env.xc8('mib12_app_module.hex', srcfiles)
symtab = env.build_symbols(['mib12_app_module_symbols.h', 'mib12_app_module_symbols.stb'],['mib12_app_module.sym'])

Clean(target, ['#funclist', '#l.obj'])