#gsm_module
#Momo Core Module v2.0
#By Tim Burke (7/21/2015)

#Module Information
ModuleName = "gsmcom";
ModuleVersion = "1.0.0";
APIVersion = "1.1";

#Supported Feature Information
#feature 10
2560: _gsm_rpc_on(0, no);
2561: _gsm_rpc_register(0, no);
2562: _gsm_rpc_sendcommand(0, yes);
2563: _gsm_rpc_testsim(0, no);
2565: _gsm_rpc_off(0, no);
2567: _gsm_rpc_debug(0, no);
2568: _gsm_rpc_download(0, no);
2569: _gsm_rpc_setapn(0, yes);

#Communication Channel Feature
#feature 11
2816: _gsm_rpc_openstream(1, no);
2817: _gsm_rpc_pushtostream(0, yes);
2818: _gsm_rpc_closestream(0, no);

2820: _gsm_rpc_setcommdestination(1, yes);