---
:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :release_build: TRUE
  :test_file_prefix: test_

:release_build:
  :output: MoMo-sensorboard-bootloader.hex
  :use_assembly: TRUE

:environment:

:extension:
  :object: .p1
  :executable: .hex

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
  :include:
    - +:../shared/pic12/src/**
    - +:../shared/portable/**
  :support:
    - test/support

:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :commmon: &common_defines 
    - __PIC12LF1822__
    - UNITY_INT_WIDTH=8
    - CMOCK_MEM_INDEX_TYPE=uint8_t
    - CMOCK_MEM_PTR_AS_INT=uint8_t
    - CMOCK_MEM_ALIGN=1
    - CMOCK_MEM_SIZE=8192
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

:tools:
  :release_compiler:
    :executable: xc8
    :arguments:
      - --pass1
      - --chip=12F1822
      - -Q 
      - -G 
      - --asmlist 
      - --double=24 
      - --float=24 
      - --opt=all,-asmfile
      - --addrqual=require 
      - --mode=pro 
      - -P 
      - -N31  
      - --warn=0 
      - --summary=default,+psect,-class,+mem,-hex,-file 
      - --output=default,-inhx032 
      - --runtime=default,+clear,+init,-keep,-no_startup,+osccal,+oscval:0,-resetbits,-download,+stackcall,+clib #"--errformat=%f:%l: error: %s" "--warnformat=%f:%l: warning: %s" "--msgformat=%f:%l: advisory: %s" 
      #- -L-pstrings=CODE
      - "${1}"
      - -o${2}
      - -I"$": COLLECTION_PATHS_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_RELEASE_TOOLCHAIN_INCLUDE
      - -D$: COLLECTION_DEFINES_RELEASE_AND_VENDOR

  :release_assembler:
    :executable: xc8 
    :arguments:
      - --pass1
      - --chip=12F1822 
      - -Q 
      - -G 
      - --asmlist 
      - --double=24 
      - --float=24 
      - --opt=all,-asmfile
      - --addrqual=require 
      - --mode=pro 
      - -P 
      - -N31  
      - --warn=0 
      - --summary=default,+psect,-class,+mem,-hex,-file 
      - --output=default,-inhx032 
      - --runtime=default,+clear,+init,-keep,-no_startup,+osccal,+oscval:0,-resetbits,-download,+stackcall,+clib #"--errformat=%f:%l: error: %s" "--warnformat=%f:%l: warning: %s" "--msgformat=%f:%l: advisory: %s" 
      #- -L-pstrings=CODE
      - "${1}"
      - -o${2}
      - -I"$": COLLECTION_PATHS_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_RELEASE_TOOLCHAIN_INCLUDE
      - -D$: COLLECTION_DEFINES_RELEASE_AND_VENDOR

  :release_linker:
    :executable: xc8 
    :arguments:
      - --chip=12F1822
      - -G 
      - -m./build/release/MoMo-sensorboard-bootloader.map
      - --asmlist 
      - --double=24 
      - --float=24
      #- --rom=0-44F 
      - --ram=default,-20-6D
      - --opt=all,-asmfile
      - --addrqual=require 
      - --mode=pro 
      - -P 
      - -N31  
      - --warn=0 
      - --summary=default,+psect,-class,+mem,-hex,-file 
      - --output=default,-inhx032 
      - --runtime=default,+clear,+init,-keep,-no_startup,+osccal,+oscval:0,-resetbits,-download,+stackcall,+clib #"--errformat=%f:%l: error: %s" "--warnformat=%f:%l: warning: %s" "--msgformat=%f:%l: advisory: %s" 
      #- -L-pstrings=CODE
      - "${1}"
      - "../shared/pic12/build/release/libPIC12shared.lpp"
      - "../shared/pic12/src/mib/mib_hal.as"
      - "../shared/pic12/src/i2c_utilities.as"
      - "src/flash_memory.as"
      - "src/mib/slave/command_map.as"
      - -o${2}
      - -I"$": COLLECTION_PATHS_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_RELEASE_TOOLCHAIN_INCLUDE
      - -D$: COLLECTION_DEFINES_RELEASE_AND_VENDOR
      - -V

:plugins:
  :load_paths:
    - ../../tools/ceedling/plugins
    - ../../tools/ceedling-plugins
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
...
