ModuleName = "multmod";
ModuleType = 8;
ModuleFlags = 0;

feature 20
0: _check_v1(0, no);
1: _check_v2(0, no);
2: _scheduled_callback(0, no);
3: _set_damp_parameter(2, no);
4: _power_analog(1, no);
5: _acquire_voltage(0, no);
6: _acquire_pulse(0, no);
7: _number_of_pulses(0, no);
8: _read_pulse(1, no);
9: _read_periods(0, no);
10: _read_median_interval(0, no);
11: _set_push_status(1, no);