ModuleName = "ultras";
ModuleVersion = "1.0.0";
APIVersion = "1.1";

#Debug interfaces (feature 110 -> 28160)
28160: _set_power(1, no);
28161: _read_tdc7200_register(1, no);
28162: _read_tdc1000_register(1, no);
28163: _write_tdc7200_register(2, no);
28164: _write_tdc1000_register(2, no);
28165: _read_tdc7200_register24(1, no);